name: Compile LaTeX document

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Explicitly set the permission for the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dhirendra_resume-openfont.tex
          compiler: xelatex
          args: -output-directory=output  # Specify output directory
          
      - name: Copy index.html to output
        run: cp index.html output/index.html  # Copy index.html to output directory
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Directory containing your compiled PDF
          destination_dir: ./  # Directory where the site will be hosted
