name: Compile LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: deedy_resume-openfont.tex
        
      # - name: Compile LaTeX document
      #   run: latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -output-directory=output deedy_resume-openfont.tex

      - name: Upload PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Directory containing your compiled PDF
          destination_dir: resume  # Directory where the site will be hosted
